const Items = [
  {
    id: 1,
    mainImage:
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521052/123123_sc4dld.png",
    img: [
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521052/123123_sc4dld",
      "https://res-console.cloudinary.com/dn7kw9efx/thumbnails/v1/image/upload/v1716521579/cG8zX2loZzBmbg==/drilldown",
      "https://res-console.cloudinary.com/dn7kw9efx/thumbnails/v1/image/upload/v1716521579/cG8yX3VhZHNncA==/drilldown",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521578/p04_oqjnhj.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521577/po5_n6nebu.png"
    ],
    features: [
      "Home",
      "About",
      "Package",
      "Contact",
      "Blog",
      "A user can order through the Admin for Website services, Mobile Applications, Branding & Creative Content, as well as Internet Marketing & Advertising.",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "TailwindCSS",
      "React Leaflet",
      "React Hooks",
      "React icons",
      "Email JS",
      "Framer Motion",
    ],
    title: "Modern Portfolio",
    description:
      "PT. MULIA SEJATI NUSANTARA Established on June 24, 2019, a limited liability company engaged in supplier & contractor services. Then on January 22 2022 PT. MULIA SEJATI NUSANTARA Opening a new business branch in the Technology Sector which includes Website Creation, Mobile Applications, Branding, Creative Content, Digital Marketing & Advertising. This branch is called Mulia Sejati Nusantara Production or in short MSN PRODUCTION.",
    category: "business",
    liveLink: "https://mustafasir.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/porfolio3.0",
  },
  {
    id: 2,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701463/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-2_ptr4lg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701467/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-3_gjle1m.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701489/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-5_nuhniv.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701492/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-6_rkvmhd.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701496/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-7_xjm4pm.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701499/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-8_dj0qoq.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701502/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-9_d1h5a0.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701505/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-10_kbbkd4.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701506/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-11_mmspfs.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Story searching and pagination",
      "CRUD operations (Story create, read, update and delete)",
      "Upload user ımages and story ımages to the server",
      "Liking stories and adding stories to the Reading list",
      "Commenting on the story",
      "Skeleton loading effect",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
    ],
    title: "Mern Blog",
    description:
      "Fullstack open source blogging application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "personal",
    liveLink: "https://developer-mustafa.vercel.app/mern-blog",
    codeLink: "https://github.com/developer-mustafa/mern-blog-v2",
  },
  {
    id: 3,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312777/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-2_ar1fex.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312780/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-3_qpebgb.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312777/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-4_yadwtg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312780/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-5_xvx0vj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312773/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-6_aaq4yf.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312772/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-7_twij3j.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312773/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-8_njclct.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312774/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-9_zg1jfe.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312772/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-10_yag7bj.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Add Favorites",
      "Delete Favorites",
      "Leave a Reviews",
      "Delete Reviews",
      "Password Update",
      "Search Live",
      "Watch the trailer on Youtube",
      "404 Page and many more",
      "Skeleton loading effect",
      "DarkMode",
      "DarkMode",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Router Dom",
      "Axios",
      "Material UI",
      "CK Editor",
      "Formik",
      "React Redux",
      "React Toastify",
      "Swiper",
      "NodeJS",
      "ExpressJS",
      "Mongoose",
      "Json Web Token",
      "Cookie Parser",
      "Cors",
      "Dontenv",
      "Express Validator",
      "Nodemon",
      "MongoDB",
      "TMDB API",
    ],
    title: "VisionFlix",
    description:
      "Fullstack open source movie application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "personal",
    liveLink: "https://vision-flix-mern.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/vision-flix-mern",
  },
  {
    id: 4,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-2_vsab0u.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-1_gywmlj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-2_vsab0u.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-3_ktppfh.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-4_g9pcqp.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-5_cugdqq.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-6_d550ha.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-7_u2td2u.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-8_tt0tqg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-9_thcxyv.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-10_wwmqty.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-11_issyrd.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-12_visvli.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-13_dqy6wg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-14_kvaem7.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772432/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-15_pzdxsu.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-16_ven89o.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772432/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-17_wjwedp.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682772432/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-18_zpsewd.png",
    ],
    features: [
      "Login Admin",
      "Add employee",
      "Edit employee",
      "Remove employee",
      "Add position",
      "Edit position",
      "Remove position",
      "Display data, input attendance, edit attendance and delete employee absences",
      "Employee Salary Deduction Setting",
      "Display data, input salary data, edit salary data and delete employee salary data",
      "Print payroll reports, absences, and payslips",
      "Change admin and employee passwords",
      "Login Employees/Staff",
      "Print employees/staff salary reports from personal accounts",
      "404 Page and many more",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "React Vite",
      "Redux",
      "Redux Toolkit",
      "Tailwind CSS",
      "Apexcharts",
      "Localforage",
      "Match Sorter",
      "Axios",
      "Node JS",
      "Express JS",
      "MySQL",
      "Cors",
      "JWT",
      "Bycrypt",
      "Cookie Parser",
      "Dotenv",
      "MySQL 12",
      "Nodemon",
      "Sequelize",
    ],
    title: "Employee Management",
    description:
      "Warehouse website with employee/employee management, add employee and job title options. Employee attendance data setting salary deductions and salary data. Print salary reports, attendance and salary data and many other features.",
    category: "business",
    liveLink: "https://developer-mustafa.vercel.app/employee-salary-management",
    codeLink:
      "https://github.com/developer-mustafa/mern-employee-salary-management",
  },
  {
    id: 5,
    mainImage:
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518814/projects1/c816pgwwjrfdy4bmpzzu.png",
    img: [
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518814/projects1/c816pgwwjrfdy4bmpzzu.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518814/xrwva2qgfdkqv8j1ltyj.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518813/f3xta7xidknarokybszf.png",
      "https://res-console.cloudinary.com/dn7kw9efx/thumbnails/v1/image/upload/v1716519682/bTdfajB3bnN4/drilldown",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518824/zxemkqvlzjrcmoxs3tdj.png",
    ],
    features: [
      "Student Information Management Efficiently store and manage student profiles, including personal details, academic records, and attendance.Easy access to student histories and progress reports.Course and Curriculum Management",
      
      "Create and organize courses, manage syllabi, and track curriculum changes.Simplify scheduling with an integrated calendar for classes, exams, and events.Attendance Tracking",
      
      "Real-time attendance monitoring with automated alerts for absences or tardiness.Detailed attendance reports for students and classes.Grade Management",
      
      "Record and calculate grades with ease.Generate report cards and transcripts that can be shared digitally.Communication Tools",
      
      "Facilitate communication between teachers, students, and parents through a built-in messaging system.Notifications for important updates and reminders.Financial Management",
      
      "Manage tuition fees, generate invoices, and track payments.Financial reports and analytics to keep track of the institution’s finances.Library Management",
      
      "Keep track of book inventories, check-outs, and returns.Integrated search feature for students and staff to locate books easily.Hostel and Transport Management",
      
      "Organize hostel accommodations and manage room allocations.Plan and monitor transportation routes and schedules for students.Examination and Assessment",
      
     " Schedule exams, create question papers, and manage online assessments.Analyze performance with detailed reports and statistics.Parental Access",
      
      "Provide parents with access to their child’s academic and attendance records.Enable parents to stay engaged with school activities and communicate with teachers.Customizable Dashboard",
      
     "Personalize the dashboard for different user roles, providing relevant information at a glance.Real-time analytics and reporting for quick decision-making."
    ],
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "PHP",
      "MYSQL",
      "Custom code",
    ],
    title: "Full Stack Student Management System website",
    description:"Fullstack BenefitsImproved Efficiency: Automate routine tasks and reduce manual paperwork.Enhanced Communication: Strengthen connections between educators, students, and parents.Data-Driven Insights: Use analytics to drive improvements in educational outcomes.User-Friendly Interface: Intuitive design ensuring ease of use for all users.Scalability: Adaptable to institutions of all sizes, from small schools to large universities.Security: Robust security measures to protect sensitive information and ensure data privacy.",
    category: "Full Education Management Solution",
    liveLink: "https://mithacharaifm.com/",
    codeLink:"https://github.com/developer-mustafa",
  },
  {
    id: 6,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-1_gpiiro.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-3_sk2hyn.png",
    ],
    features: [
      "Mobile Responsive",
      "Beautiful Animations",
      "Rapid Controls",
      "High Score",
      "Mario Background Music",
      "Jump & Game Over Sound Effect",
    ],
    technologies: [
      "React",
      "CSS",
      "React Hooks",
      "React Router",
      "React Redux",
    ],
    title: "Mario Jump",
    description:
      "Mario Jump is an endless running game inspired by the famous Google Chrome's T-Rex Dinosaur Game 🦖. The game is built entirely with ReactJS ⚛ and Redux Toolkit 🔧.",
    category: "game",
    liveLink: "https://mariojumpp.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/mario-jump-game",
  },
  {
    id: 7,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-2_ukjdh2.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-4_btevir.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-5_oakjx2.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944092/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-6_pqefy9.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-7_wfrvb7.png",
    ],
    features: [
      "User registration and login",
      "Select the type of question and the difficulty level of the question",
      "Juis time is running and after the time is up it stops automatically",
      "The final results of the answers answered will be shown",
      "Incorrect and correct answer results will be displayed",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Vite",
      "Tailwind CSS",
      "Firebase Authentication",
      "Framer Motion",
      "React Firebase Hooks",
      "React Icons",
    ],
    title: "Bert Quiz",
    description: "Fullstack open source quiz application",
    category: "personal",
    liveLink: "https://bertquiz.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/react-quiz",
  },
  {
    id: 8,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033411/Blog%20Portfolio%20Gilbert/Project/shopify/img-2_nko9ic.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033413/Blog%20Portfolio%20Gilbert/Project/shopify/img-3_rnhbr1.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-4_ks8lck.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033409/Blog%20Portfolio%20Gilbert/Project/shopify/img-5_eotroj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-6_fgpzef.png",
    ],
    features: [
      "Mobile Responsive",
      "Beautiful Animations",
      "Product",
      "Pricing",
      "Testimonial",
      "Contact",
    ],
    technologies: [
      "React",
      "React Vite",
      "Tailwind CSS",
      "Framer Motion",
      "React Icons",
      "React Hooks",
    ],
    title: "Shopify",
    description: "Open source landing page shopify application",
    category: "personal",
    liveLink: "https://shopifyy.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/react-shopify-landing",
  },
];

export default Items;
