const Items = [
  {
    id: 1,
    mainImage:
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521052/123123_sc4dld.png",
    img: [
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521052/123123_sc4dld",
      "https://res-console.cloudinary.com/dn7kw9efx/thumbnails/v1/image/upload/v1716521579/cG8zX2loZzBmbg==/drilldown",
      "https://res-console.cloudinary.com/dn7kw9efx/thumbnails/v1/image/upload/v1716521579/cG8yX3VhZHNncA==/drilldown",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521578/p04_oqjnhj.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716521577/po5_n6nebu.png"
    ],
    features: [
      "Home",
      "About",
      "Package",
      "Contact",
      "Blog",
      "A user can order through the Admin for Website services, Mobile Applications, Branding & Creative Content, as well as Internet Marketing & Advertising.",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "TailwindCSS",
      "React Leaflet",
      "React Hooks",
      "React icons",
      "Email JS",
      "Framer Motion",
    ],
    title: "Modern Portfolio",
    description:
      "PT. MULIA SEJATI NUSANTARA Established on June 24, 2019, a limited liability company engaged in supplier & contractor services. Then on January 22 2022 PT. MULIA SEJATI NUSANTARA Opening a new business branch in the Technology Sector which includes Website Creation, Mobile Applications, Branding, Creative Content, Digital Marketing & Advertising. This branch is called Mulia Sejati Nusantara Production or in short MSN PRODUCTION.",
    category: "business",
    liveLink: "https://mustafasir.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/porfolio3.0",
  },
  {
    id: 2,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701463/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-2_ptr4lg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701467/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-3_gjle1m.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701489/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-5_nuhniv.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701492/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-6_rkvmhd.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701496/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-7_xjm4pm.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701499/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-8_dj0qoq.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701502/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-9_d1h5a0.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701505/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-10_kbbkd4.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701506/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-11_mmspfs.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Story searching and pagination",
      "CRUD operations (Story create, read, update and delete)",
      "Upload user ımages and story ımages to the server",
      "Liking stories and adding stories to the Reading list",
      "Commenting on the story",
      "Skeleton loading effect",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
    ],
    title: "Mern Blog",
    description:
      "Fullstack open source blogging application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "personal",
    liveLink: "https://developer-mustafa.vercel.app/mern-blog",
    codeLink: "https://github.com/developer-mustafa/mern-blog-v2",
  },
  {
    id: 3,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312777/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-2_ar1fex.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312780/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-3_qpebgb.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312777/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-4_yadwtg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312780/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-5_xvx0vj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312773/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-6_aaq4yf.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312772/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-7_twij3j.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312773/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-8_njclct.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312774/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-9_zg1jfe.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1684312772/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-10_yag7bj.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Add Favorites",
      "Delete Favorites",
      "Leave a Reviews",
      "Delete Reviews",
      "Password Update",
      "Search Live",
      "Watch the trailer on Youtube",
      "404 Page and many more",
      "Skeleton loading effect",
      "DarkMode",
      "DarkMode",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Router Dom",
      "Axios",
      "Material UI",
      "CK Editor",
      "Formik",
      "React Redux",
      "React Toastify",
      "Swiper",
      "NodeJS",
      "ExpressJS",
      "Mongoose",
      "Json Web Token",
      "Cookie Parser",
      "Cors",
      "Dontenv",
      "Express Validator",
      "Nodemon",
      "MongoDB",
      "TMDB API",
    ],
    title: "VisionFlix",
    description:
      "Fullstack open source movie application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "personal",
    liveLink: "https://vision-flix-mern.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/vision-flix-mern",
  },
  {
    id: 4,
    mainImage:
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716522962/chart1_yukjqt.png",
    img: [
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716522962/chart1_yukjqt.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716522962/chart3_kyildx.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716522962/chart2_imyfdc.png",
     
    ],
    features: [
      "Login Admin",
      "Add employee",
      "Edit employee",
      "Remove employee",
      "Add position",
      "Edit position",
      "Remove position",
      "Display data, input attendance, edit attendance and delete employee absences",
      "Employee Salary Deduction Setting",
      "Display data, input salary data, edit salary data and delete employee salary data",
      "Print payroll reports, absences, and payslips",
      "Change admin and employee passwords",
      "Login Employees/Staff",
      "Print employees/staff salary reports from personal accounts",
      "404 Page and many more",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "React Vite",
      "Redux",
      "Redux Toolkit",
      "Tailwind CSS",
      "Apexcharts",
      "Localforage",
      "Match Sorter",
      "Axios",
      "Node JS",
      "Express JS",
      "MySQL",
      "Cors",
      "JWT",
      "Bycrypt",
      "Cookie Parser",
      "Dotenv",
      "MySQL 12",
      "Nodemon",
      "Sequelize",
    ],
    title: "React Admin Dashboard",
    description:"Analytics and Reports Real-time data visualization: Track key metrics and performance indicators with interactive charts and graphs. Customizable reports: Generate and export detailed reports tailored to your business needs. System settings: Configure application settings to match your business requirements. Personal preferences: Customize your dashboard experience with theme options and layout preferences. 7. Security and Compliance. Data protection: Ensure data security with advanced encryption and secure authentication mechanisms. Regulatory compliance: Stay compliant with industry standards and regulations. User Interface Intuitive Design. User-friendly layout: Navigate through a clean and responsive interface designed for efficiency. Dashboard widgets: Personalize your dashboard with drag-and-drop widgets to prioritize important information. Customizable Themes. Light and dark modes: Choose between different themes to reduce eye strain and improve usability. Theme customization: Modify colors and styles to align with your brand identity. Integration and Extensibility API Integrations. Third-party services: Seamlessly integrate with external services like payment gateways, CRMs, and more. Custom APIs: Extend functionality with custom API endpoints tailored to your specific needs. Modular Architecture. Component-based design: Build and maintain the dashboard with reusable React components. Scalable solutions: Ensure your dashboard can grow with your business by adding new features effortlessly.",
    category: "business analytics",
    liveLink: "https://next-js-admin-dashboard-pi.vercel.app/",
    codeLink:
      "https://github.com/developer-mustafa/NextJS-admin-dashboard",
  },
  {
    id: 5,
    mainImage:
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518814/projects1/c816pgwwjrfdy4bmpzzu.png",
    img: [
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518814/projects1/c816pgwwjrfdy4bmpzzu.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518814/xrwva2qgfdkqv8j1ltyj.png",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518813/f3xta7xidknarokybszf.png",
      "https://res-console.cloudinary.com/dn7kw9efx/thumbnails/v1/image/upload/v1716519682/bTdfajB3bnN4/drilldown",
      "https://res.cloudinary.com/dn7kw9efx/image/upload/v1716518824/zxemkqvlzjrcmoxs3tdj.png",
    ],
    features: [
      "Student Information Management Efficiently store and manage student profiles, including personal details, academic records, and attendance.Easy access to student histories and progress reports.Course and Curriculum Management",
      
      "Create and organize courses, manage syllabi, and track curriculum changes.Simplify scheduling with an integrated calendar for classes, exams, and events.Attendance Tracking",
      
      "Real-time attendance monitoring with automated alerts for absences or tardiness.Detailed attendance reports for students and classes.Grade Management",
      
      "Record and calculate grades with ease.Generate report cards and transcripts that can be shared digitally.Communication Tools",
      
      "Facilitate communication between teachers, students, and parents through a built-in messaging system.Notifications for important updates and reminders.Financial Management",
      
      "Manage tuition fees, generate invoices, and track payments.Financial reports and analytics to keep track of the institution’s finances.Library Management",
      
      "Keep track of book inventories, check-outs, and returns.Integrated search feature for students and staff to locate books easily.Hostel and Transport Management",
      
      "Organize hostel accommodations and manage room allocations.Plan and monitor transportation routes and schedules for students.Examination and Assessment",
      
     " Schedule exams, create question papers, and manage online assessments.Analyze performance with detailed reports and statistics.Parental Access",
      
      "Provide parents with access to their child’s academic and attendance records.Enable parents to stay engaged with school activities and communicate with teachers.Customizable Dashboard",
      
     "Personalize the dashboard for different user roles, providing relevant information at a glance.Real-time analytics and reporting for quick decision-making."
    ],
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "PHP",
      "MYSQL",
      "Custom code",
    ],
    title: "Full Stack Student Management System website",
    description:"Fullstack BenefitsImproved Efficiency: Automate routine tasks and reduce manual paperwork.Enhanced Communication: Strengthen connections between educators, students, and parents.Data-Driven Insights: Use analytics to drive improvements in educational outcomes.User-Friendly Interface: Intuitive design ensuring ease of use for all users.Scalability: Adaptable to institutions of all sizes, from small schools to large universities.Security: Robust security measures to protect sensitive information and ensure data privacy.",
    category: "Full Education Management Solution",
    liveLink: "https://mithacharaifm.com/",
    codeLink:"https://github.com/developer-mustafa",
  },
 
  {
    id: 6,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-2_ukjdh2.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-4_btevir.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-5_oakjx2.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944092/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-6_pqefy9.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-7_wfrvb7.png",
    ],
    features: [
      "User registration and login",
      "Select the type of question and the difficulty level of the question",
      "Juis time is running and after the time is up it stops automatically",
      "The final results of the answers answered will be shown",
      "Incorrect and correct answer results will be displayed",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Vite",
      "Tailwind CSS",
      "Firebase Authentication",
      "Framer Motion",
      "React Firebase Hooks",
      "React Icons",
    ],
    title: "Bert Quiz",
    description: "Fullstack open source quiz application",
    category: "personal",
    liveLink: "https://bertquiz.vercel.app/",
    codeLink: "https://github.com/developer-mustafa/react-quiz",
  },
  
];

export default Items;
